# Generated by Django 4.2.7 on 2023-11-08 03:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=191)),
                ('Skill', models.CharField(default=None, max_length=191)),
                ('Fee', models.IntegerField(default=None)),
                ('cell_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('experience', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
