# Generated by Django 4.2.7 on 2023-11-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cell_num',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='Price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='service',
            name='ServiceName',
            field=models.CharField(default=None, max_length=191),
        ),
        migrations.AddField(
            model_name='service',
            name='Title',
            field=models.CharField(default=None, max_length=191),
        ),
    ]
