# Generated by Django 4.2.7 on 2023-11-22 17:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home_services', '0002_remove_service_cell_num_remove_service_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=191)),
                ('cell_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Address', models.CharField(default=None, max_length=50)),
                ('ServiceTitle', models.CharField(max_length=50)),
                ('TimeAndDate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=191)),
                ('Skill', models.CharField(default=None, max_length=191)),
                ('CNIC', models.CharField(default=None, max_length=15, unique=True)),
                ('Licence', models.CharField(default=None, max_length=20, unique=True)),
                ('Fee', models.IntegerField(default=None)),
                ('cell_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('experience', models.CharField(default=None, max_length=50)),
                ('Area', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
