# Generated by Django 4.2.7 on 2023-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_services', '0004_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Address',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
